# ==============================
# Ajisai (AMDIM-style) SSL Config
# ==============================

model:
  name: AjisaiModel
  encoder: resnet18
  projection_dim: 128
  feature_dim: 512

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.0003
  optimizer: Adam
  weight_decay: 1e-4
  temperature: 0.07
  num_workers: 2
  device: cuda

dataset:
  name: MangoLeafBD
  root: "/kaggle/input/mango-leaf-disease-dataset"
  image_size: 224
  augmentations: strong

loss:
  name: InfoNCE
  margin: 0.0
  temperature: 0.07

fewshot:
  n_way: 5
  n_shot: 5
  n_query: 15
  test_split: 0.2
